[package]
name = "ListaSimple"
version = "0.1.0"
edition = "2024"

# Documentación de Cargo: https://doc.rust-lang.org/stable/cargo/

[dependencies]
colored = "3.0.0"
once_cell ={ version = "1.20.2"}
# Dpendencias grficas
eframe = "0.31.1"
egui = "0.31.1"